[build-system]
requires = ["setuptools>=61.0.0"]
backend = "setuptools.build_meta"

[project]
name = "workspace"
version = "0.1.0"
description = "E-commerce customer churn, segmentation and revenue risk analysis pipeline"
dependencies = [] # requirements.txt manage packages

[tool.setuptools.packages.find]
where = ["."]